### ISSUE TITLE
No prevention against JWT reuse?

### ISSUE THREAD

**Issue by joesiltberg** [skolverket/dnp-ss12000-reference-api#1]
I can't find any validation of the audience claim in the JWT token for the authentication to the SS12000 API. If we receive a valid JWT token from Skolverket, what is preventing us from using that token to make requests to another organisation's SS12000 API?

If I run the provisioning-reference-api with SS12000_AUTH_JWKS_URI set to https://nutid-auth-test.sunet.se/.well-known/jwks.json it seems to allow access to anyone with a token issued by that authorization server.

**Comment by GustafNilstadius** [comment]
Valid concern that currently does not have a solution and needs to be addressed before going live. I've have previously been looking at the possibility of setting claims (such as the aforementioned `aud`) in the JWT and verifying them in provisioning-reference-api.  
However the audience claim is populated by other data from sunet at the moment, but there's a possibility in the GNAP core protocol to use the `requested_access` claim with `locations`, still undecided but the question is being processed. 
Another problem is that there currently isn't a consensus on what the location should be set to for each _Huvudman_ and where to source the information. Perhaps setting the location to the base path of the SS12000 API would be a good solution (and my preferred solution) e.g. "https://provisioning-reference-api-dev-example.skolverket.se/base/path/ss12000/" as it will be available on the client side (Skolverket) and provided by the _Huvudman_ while registering the SS12000  API. Thoughts @joesiltberg ?   

> If I run the provisioning-reference-api with SS12000_AUTH_JWKS_URI set to https://nutid-auth-test.sunet.se/.well-known/jwks.json it seems to allow access to anyone with a token issued by that authorization server.   

Expected behavior as there's not validation of the `scope`, `entity_id` or `organization_id` (organisationsnummer) claims yet.

**Comment by joesiltberg** [comment]
> Perhaps setting the location to the base path of the SS12000 API would be a good solution (and my preferred solution) e.g. "https://provisioning-reference-api-dev-example.skolverket.se/base/path/ss12000/" as it will be available on the client side (Skolverket) and provided by the Huvudman while registering the SS12000 API. Thoughts @joesiltberg ?

Sounds good to me!

**Comment by nighal** [comment]
@joesiltberg 
We have now added detailed instruction on how school principals should verify JWT that they receive from Skoloverket's SS12000-Client. You can find the instruction here: https://github.com/skolverket/dnp-usermanagement/tree/main/authentication-api#verifiering-av-jwt-som-skickas-fr%C3%A5n-provtj%C3%A4nstens-ss12000-klient.
