### ISSUE TITLE
Missing attribute?

### ISSUE THREAD

**Issue by mattiasmelin** [skolverket/dnp-ss12000-reference-api#12]
Is externalIdentifiers expected to be available when Skolverket pull data?
In that case the property is missing here:
https://github.com/skolverket/dnp-ss12000-reference-api/blob/03ec250d520dc71ae4bcb183cb98f7acd1a8012c/src/main/resources/openapi/expose/openapi/openapi.yml#L653

I found reference to it when pushing data, here:
https://github.com/skolverket/dnp-usermanagement/blob/main/provisioning-api/dnp-provisioning-api.yaml#L1849

**Comment by mattiasmelin** [comment]
Created related query to Skolverket support and will see if I can get clarification if the attribute is expected or not.

**Comment by GustafNilstadius** [comment]
See Person class. 
`  private List<ExternalIdentifier> externalIdentifiers;`   
https://github.com/skolverket/dnp-ss12000-reference-api/blob/03ec250d520dc71ae4bcb183cb98f7acd1a8012c/src/main/java/se/skolverket/service/provisioning/provisioningreferenceapi/services/persons/model/Person.java#L46C1-L46C56

Due to time constants, maintaining the two OpenAPI files in this project is not the highest priority. As it reads in the OpenAPI specification; 

> Specification might not correspond to the actual implementation. The code serves as absolute documentation.  
  
As for if it's expected or not, that's specified in the above linked [dnp-usermanagement](https://github.com/skolverket/dnp-usermanagement) repo. 

Tagging issue as `documentation`. Will be fixed in an upcoming release.

**Comment by GustafNilstadius** [comment]
Fix pushed. Closing issue.
